security:
    enable_authenticator_manager: true

    # --- PROVIDERS ---
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # --- FIREWALLS ---
    firewalls:
        # Aucune sécurité pour les assets et le profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Utilisation du KeycloakAuthenticator comme point d'entrée
            entry_point: App\Security\KeycloakAuthenticator

            custom_authenticators:
                - App\Security\KeycloakAuthenticator

            # Route de déconnexion
            logout:
             path: /logout/keycloak
             target: /


        # --- ACCESS CONTROL ---
    access_control:
        - { path: ^/logout/keycloak, roles: PUBLIC_ACCESS }
        - { path: ^/oauth, roles: PUBLIC_ACCESS }
        - { path: ^/cgu, roles: PUBLIC_ACCESS }
        
        # 1. On autorise l'accès à la racine "/" pour TOUT LE MONDE
        - { path: ^/$, roles: PUBLIC_ACCESS }
        
        # 2. On protège spécifiquement l'administration
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        # 3. Optionnel : On protège le reste si nécessaire, 
        # mais attention à ne pas bloquer les pages de formations publiques !
        # - { path: ^/, roles: ROLE_USER } 
